//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clients()
        {
            this.Colis = new HashSet<Colis>();
            this.Commandes = new HashSet<Commandes>();
        }
    
        public int Id_Client { get; set; }
        public string Nom_Client { get; set; }
        public string Nom_Societe { get; set; }
        public string Prenom_client { get; set; }
        public Nullable<int> Coefficient_Client { get; set; }
        public string Telephone_Client { get; set; }
        public string Ville_Client { get; set; }
        public string Adresse_Client { get; set; }
        public string Code_Postal { get; set; }
        public Nullable<bool> Professionnel { get; set; }
        public Nullable<int> Ref_Commercial_clie { get; set; }
    
        public virtual Commerciaux Commerciaux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Colis> Colis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commandes> Commandes { get; set; }
    }
}
