//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composer
    {
        public Nullable<int> Quantite { get; set; }
        public Nullable<decimal> Prix_Coefficient { get; set; }
        public int Ref_Produit_Comp { get; set; }
        public int Ref_commande_Comp { get; set; }
    
        public virtual Commandes Commandes { get; set; }
        public virtual Produits Produits { get; set; }
    }
}
