//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Village_GreenEntities : DbContext
    {
        public Village_GreenEntities()
            : base("name=Village_GreenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Colis> Colis { get; set; }
        public virtual DbSet<Commandes> Commandes { get; set; }
        public virtual DbSet<Commerciaux> Commerciaux { get; set; }
        public virtual DbSet<Composer> Composer { get; set; }
        public virtual DbSet<Fournisseurs> Fournisseurs { get; set; }
        public virtual DbSet<Produits> Produits { get; set; }
        public virtual DbSet<Sous_Categories> Sous_Categories { get; set; }
    }
}
