//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produits()
        {
            this.Composer = new HashSet<Composer>();
        }
    
        public int Id_Produit { get; set; }
        public string Description_Produit { get; set; }
        public string Libelle_Produit { get; set; }
        public string Photo_Produit { get; set; }
        public Nullable<decimal> Prix_HT_Produit { get; set; }
        public Nullable<decimal> Prix_Achat_Fournisseur { get; set; }
        public Nullable<int> Stock_Produit { get; set; }
        public Nullable<bool> Publication_Produit { get; set; }
        public string Ref_Nom_Sous_Categorie_Prod { get; set; }
        public Nullable<int> Ref_Fournisseur_Prod { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Composer> Composer { get; set; }
        public virtual Fournisseurs Fournisseurs { get; set; }
        public virtual Sous_Categories Sous_Categories { get; set; }
    }
}
